### ISSUE TITLE
Add timestamp in log ?

### ISSUE THREAD

**Issue by niawag** [ShiromMakkad/docker-pihole-sync#14]
Hi and thanks a lot for this docker, it works great and is really useful, congrats!

I had some configuration issues and had to check the log to troubleshoot and got it working but the lack of timestamp in the log file made it harder.
Is it already possible to add it ? If not, is it a part of your plan or may I try to add this "feature" ?

**Comment by kaechele** [comment]
Would the `-t` option of `docker logs` do what you need?

**Comment by niawag** [comment]
It does ! Thanks a lot for your help, I had no idea this was an option of this command!
