### ISSUE TITLE
Arm64

### ISSUE THREAD

**Issue by metalwolfy** [ShiromMakkad/docker-pihole-sync#7]
Hi,
This looks like a great project!  I was wondering if it would be possible to have an Arm64 version made available on docker hub?  I'm looking to set it up on my ubuntu running pi 4 8gb.

Thanks.

**Comment by devros42** [comment]
Would be great to be able to run this on my Pi4 with 64bit Cent8.  it's just what I've been looking for.

**Comment by ShiromMakkad** [comment]
Yea, I haven't been working on this project for a bit. Idk when I'll get back to it, but I'm pretty sure you can run normal arm binaries on the pi 4 with a 64 bit os. You can try the normal binaries.
